### ISSUE TITLE
AttributeError: 'UpYun' object has no attribute 'up_rest'

### ISSUE THREAD

**Issue by alanwangmodify** [upyun/python-sdk#45]
`
up = upyun.UpYun('****', secret='*****', endpoint=upyun.ED_AUTO)   

 with open('contentImg.jpg', 'rb') as f:   
        res = up.put('/style/xinu.jpg', f, checksum=True, need_resume=True)
`
一直 报错 ：
AttributeError: 'UpYun' object has no attribute 'up_rest'

**Comment by huangnauh** [comment]
只有 rest api 支持断点续传, 需要 username 和 password
`up = upyun.UpYun('bucket', username='username', password='password')`

**Comment by alanwangmodify** [comment]
好的，谢谢，问题解决了，是想要表单上传，弄错代码了
