### ISSUE TITLE
请教大神关于计算FORM API上传方式签名的问题

### ISSUE THREAD

**Issue by duzhipeng** [upyun/python-sdk#52]
很抱歉在您百忙之中打扰您。

我希望使用SDK提供的【远程签名服务】，但需要计算出的签名是用于FORM API 。几经使用计算出来的签名总是被【signature error】，对照源码检查了半天也查不出哪里出错了。猜测可能policy这步问题比较大，不知道能否把计算policy的方法接口也开放了，可以直接提交相关参数然后得到FORM API的签名，而不必像现在如果需要FORM API 的签名，得自己实现policy之后传入。

或者，能否在auth_server.py提供一下FORM API的实现，我照着大神的写法排查下问题。

也阅读了SDK中policy的计算，但修改下用在python3下怎么也不好使。

**Comment by yejingx** [comment]
policy 的计算在[这里](https://github.com/upyun/python-sdk/blob/master/upyun/modules/sign.py#L42)，其它就是 json 化+base64。如果你用的是 python，可以直接调用这个函数。

**Comment by duzhipeng** [comment]
> policy 的计算在这里，其它就是 json 化+base64。如果你用的是 python，可以直接调用这个函数。

嗯，刚才测试了使用旧签名方法，可以通过接口验证。说明policy的计算是没问题的，所以怀疑在签名那块。签名之前是调用大神SDK里提供的方法，现在正在自己重写，看看是不是这里面有问题。

**Comment by duzhipeng** [comment]
解决了。给大家参考：URI参数的问题，这个参数换作后台要提交，前台部分请求的时候，也要一致。
