### ISSUE TITLE
改版后不需要bucket了？

### ISSUE THREAD

**Issue by quanjin9099** [upyun/python-sdk#65]
upyun.modules.exception.UpYunServiceException: ('329cdd4c0b4a1061c01c55081d2a00bb', 400, 'Bad Request', '{"msg":"need bucket name","code":40000003,"id":"329cdd4c0b4a1061c01c55081d2a00bb"}')

**Comment by hzjsea** [comment]
这么一个issues 3年都没更新哈哈哈哈哈

**Comment by huangnauh** [comment]
> upyun.modules.exception.UpYunServiceException: ('329cdd4c0b4a1061c01c55081d2a00bb', 400, 'Bad Request', '{"msg":"need bucket name","code":40000003,"id":"329cdd4c0b4a1061c01c55081d2a00bb"}')

因为入口 `bucket` 改名了，改成了 `service`
